### PR TITLE
docs: relicense code under Apache 2.0 with LLVM exceptions

### PR DESCRIPTION
**Pull request by favonia**
@symgryph @JvdMaat I'm considering relicensing the entire project under the Apache 2.0 license **with LLVM exceptions** to improve compatibility with GPL 2.0 and many runtime license exceptions.

You've previously contributed to this project (thank you!), so I need your approval to proceed with relicensing. If you don't approve, I may need to remove or replace your contribution before relicensing.

Let's keep the process as simple as possible: **to indicate your agreement, please approve this pull request.**

### CODE REVIEW

**Review by skarekrow — APPROVED** [review]

**Comment by favonia** [comment]
Alright, I rewrote and dropped all the parts I might not have the right to relicense.

**Comment by JvdMaat** [comment]
Looks like it's already approved.

**Comment by favonia** [comment]
@JvdMaat Just to clarified, it was only approved by one of the copyright owners. You might also own the copyright of some part of the documentation. Therefore your approval is still important, at least before I rewrote the sentences.

**Comment by symgryph** [comment]
I will approve today. I have no problem with it

Sincerely,

THOMAS MUNN
________________________________

**Pull request merged**
