### PR TITLE
ci: use fetch-depth to streamline tag fetching

### PR DESCRIPTION
**Pull request by favonia**
This is to track whether https://github.com/actions/checkout/issues/290 is fixed so that we can drop the hack to fetch all tags. This PR _should not_ be merged until the issue has been resolved.
- [ ] https://github.com/actions/checkout/issues/290

### CODE REVIEW

**Comment by favonia** [comment]
Close this for now.

**Comment by Grogogoll** [comment]
Workflow runs completed with no jobs

**Comment by Grogogoll** [comment]
Workflow runs completed with no jobs

**Comment by favonia** [comment]
@Grogogoll Hi, could you possibly explain a bit more? I have trouble understanding your comment. Did you mean that the PR actually worked? This is an old PR, so maybe not all the records are available now.

**Comment by Grogogoll** [comment]
Oups, sorry about that, I guess I made some mistake here. Well I should watch out...

**Comment by favonia** [comment]
@Grogogoll That's fine. Let me know if you notice other issues. Unfortunately I think it's still necessary to `git fetch` everything to calculate the correct version. (This is about an optimization of the CI process and should not affect how efficient the eventually built updater is, so... it's just that GitHub will spend more time building the artifacts :sweat_smile:)

**Pull request closed without merging**
