### PR TITLE
feat(droproot): support non-Linux platforms

### PR DESCRIPTION
**Pull request by skarekrow**
Thanks for your work on this! Ideally I'd be having this run on my router (OpenBSD) as a standard user, which causes obvious failures since this relies on libcap for Linux :D 

This PR is more a discussion point as I don't understand how to skip certain dependencies based on the `GOOS` received, but thought I'd show there's interest in running this outside of docker as an unprivileged user. I suspect since you can cross complie with many targets, this opens up the possibility of running on a lot of other UNIX-like systems (*BSD's come to mind)

This compiles fine and runs great on an OpenBSD host with this one dependency dropped however!

Ran using:
```
CF_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN DOMAINS=xxxx.org TZ=America/Chicago
```

### CODE REVIEW

**Comment by favonia** [comment]
See https://github.com/favonia/cloudflare-ddns/issues/728 for the plan to include a build that does exactly what you suggestied. Ideally, it should be a [build tag.](https://pkg.go.dev/cmd/go#hdr-Build_constraints) Any suggestion for the name of the alternative build that works for non-Linux?

**Comment by skarekrow** [comment]
Hah, that's serendipitous! I think the tag name of `nodrop` might be good? I'm not sure since I think the 2 usecases are _slightly_ different. On one hand, you want #728 for debugging issues like #707, but then on the other hand, we want this to be buildable on non-linux systems (like OpenBSD, macOS, etc). 

I think maybe a good start is calling it something similar to your suggestions or mine for a build tag, and having a blurb in the README mentioning that alternative operating systems should try using the $BUILDTAG instead?

**Comment by favonia** [comment]
@skarekrow Yes, the two use cases differ, but they have the same solution. ;-) I want #728 to work for _both_ reasons. Perhaps we can focus on portability and generality. I feel `nodrop` is a bit unclear... any other suggestions inspired by portability?

Or, maybe the original version should be called `noroot`?

BTW, you should have run `go mod tidy` :-)

**Comment by skarekrow** [comment]
@favonia haha i just didn't commit that after I noticed, I did now :D 

I'm honestly not sure, maybe just calling it `generic` and the other build can be `linux` for now? Let's you down the road add things that specific OS may call for that `linux` or the normal `generic` don't require themselves?

**Comment by favonia** [comment]
> it _can_ indeed still be ran as root, it's just the dropping of privilege that doesn't occur.

The DDNS updater will try very hard to change process UID and GID if it was 0 (usually the root).

**Comment by favonia** [comment]
@skarekrow I have been thinking about that but it gave me the feeling of "no limit (cap)" instead of "not manipulating capacities" :shrug: (I don't have a good idea, either.)

**Comment by favonia** [comment]
How about `setpuid` for the current version that will take `PUID`?

**Comment by favonia** [comment]
For easier migration, I slightly prefer some UI warning the user that it is no longer taking `PUID` and `PGID`. However, this can be done later if you don't have time.

**Comment by massijay** [comment]
What about `nocapdrop` or `norootdrop`?

**Comment by skarekrow** [comment]
@favonia don't worry, i haven't dropped. Just not a lot of time right now irl. I will say though, with a cursory glance at the go build flags, it doesn't seem like it will do what we want without making `droproot` a complete separate package? I'm pretty new to go packaging in general, so perhaps I'm overlooking something obvious here too.

**Comment by favonia** [comment]
> Are you against me including a sample rc file for OpenBSD users to use as well? I got it working nicely in my setup, it's quite simple!

No, but please open a new issue or a new PR for that. :slightly_smiling_face:

**Comment by skarekrow** [comment]
@favonia OK all working locally here! The build fails when the tag is not supplied, as expected.

Ex:
- `GOARCH=amd64 GOOS=openbsd go build ./cmd/ddns` -> Fail (current behavior)
- `GOARCH=amd64 GOOS=openbsd go build -tags nocapdrop ./cmd/ddns` -> Builds and runds (new behavior)

**Comment by skarekrow** [comment]
I will say that I would prefer instead that we did this by OS, so if we ever need to extend specific support elsewhere. As in something like this:
```
checker_linux.go 
config_linux.go
drop_linux.go
drop_openbsd.go
drop_linux_test.go
```
Where we can then add a `drop_freebsd` for instance that may have some unique things it needs handled instead of a no-op. The downside is the default behavior would now need a build tag of `linux` for example. But as is, I stuck to what was discussed here and kept it simple.

**Comment by favonia** [comment]
Sorry for the long radar silence. I couldn't meaningfully contribute to this project for months.

> I will say that I would prefer instead that we did this by OS, so if we ever need to extend specific support elsewhere. As in something like this:

I like this idea! Maybe a combination of OS tags and `nocapdrop`, and we always read `PGID` and `PUID`.

Theoretically none of these are needed because I already programed the testing carefully that the code should still run. Who knows why `libcap` + LXC would crash the runtime directly (and there's nothing I can do).

**Comment by favonia** [comment]
@skarekrow Do you agree with the suggested approach? If so, do you want to implement it now? If you agree but you are busy now, do you mind me hijacking this PR?

**Comment by skarekrow** [comment]
> @skarekrow Do you agree with the suggested approach? If so, do you want to implement it now? If you agree but you are busy now, do you mind me hijacking this PR?

@favonia Hijack away!

**Comment by favonia** [comment]
@skarekrow Could you test if `go run -tags nocapdrop` works for you?

**Comment by favonia** [comment]
Let me merge this first. :-) I need to test the Docker tagging.

**Pull request merged**
