### PR TITLE
feat(api): update WAF lists

### LINKED ISSUE #646: Add the ability to update Cloudflare WAF lists with detected IP addresses
Unsure if this falls within the scope of this project, but I have a feature request:

- Whenever the IP updates, in addition to updating the DNS record, add or update an IP access rule (Security>WAF>Tools) to allow the new IP.

Here are the relevant docs: [https://developers.cloudflare.com/api/operations/ip-access-rules-for-a-zone-list-ip-access-rules](https://developers.cloudflare.com/api/operations/ip-access-rules-for-a-zone-list-ip-access-rules). It seems CF does not allow the value to be edited (only mode and notes), so upon an IP change the old one would have to be deleted and a new rule with the new IP would be created. For deletion, the API supports filtering the GET results using several optional parameters, including the notes.

Let me know if I can help out in implementing this is any way.

### LINKED ISSUE #684: Feature Request: Add support for Cloudflare Access
I would love the option to whitelist my ip in a policy for an App in cloudflare Access. I have made a script to do that for me but it works not so well.

### PR DESCRIPTION
**Pull request by favonia**
Close #646. Close #684.

## Progress

- [x] Implement and test the new low-level update operations in `api`
- [x] Implement, document, and test the high-level update operations in `setter`
- [x] Implement, document, and test the detect-and-update logic in `updater`
- [x] Implement, document, and test the new logic in `config`
- [ ] `README`
  - [ ] Advertisement at the top
  - [ ] Detailed option explanations

## UI

- `WAF_LISTS=list1,list2`
- `WAF_LIST_DESCRIPTION=blah blah blah`

## Design issues

- [x] Delete all lists when exiting if `DELETE_ON_STOP=1`? **YES**
- [x] Should IPv4/6 addresses be updated if no IPv4/6 was detected? **NO**
- [x] Preserving comments and all matching ranges? **YES**

### CODE REVIEW

**Comment by favonia** [comment]
@WolfRamAlpha12 @jdvuyk @Gamerou I am happy to report that the code is this PR is working! But I still need to write test cases and documentation. Some design questions:

1. Do `WAF_LISTS` and `WAF_LIST_DESCRIPTION` look intuitive and reasonable to you? (That is, do you know how to use them without reading the documentation?)
2. If there's already a very wide IP range covering the detected IP, should we keep it intact? For example, maybe the IP is `10.0.0.1` and there's already a super wide range `10.0.0.1/8`. Should we keep the wide range instead?
3. The current code will destroy all comments attached to individual IP addresses/ranges and might not preserve their order between updates. Please let me know if this would be an issue. (I might change the code to preserve all comments before merging this PR, though.)

**Comment by Gamerou** [comment]
> @WolfRamAlpha12 @jdvuyk @Gamerou I am happy to report that the code in this PR is working (updating my personal list as expected)! But I still need to write test cases and documentation. Some design questions for you:
> 
> 
> 
> 1. Do `WAF_LISTS` and `WAF_LIST_DESCRIPTION` look intuitive and reasonable to you? (That is, do you know how to use them without reading the documentation?)
> 
> 2. If there's already a very wide IP range covering the detected IP, should we keep it intact? For example, maybe the IP is `10.0.0.1` and there's already a super wide range `10.0.0.1/8` in the list. Should we keep the wide range instead?
> 
> 3. The current code will destroy all comments attached to individual IP addresses/ranges and might not preserve their order between updates. Please let me know if this would be an issue. (I might change the code to preserve all comments before merging this PR, though.)

Hi,

Great to hear that the code is working as expected! Here are my thoughts on your design questions:

1. WAF_LISTS and WAF_LIST_DESCRIPTION:
They seem intuitive and reasonable to me. Without having seen the documentation, I can understand their intended use.

2. Handling Wide IP Ranges:
If there's already a very wide IP range covering the detected IP, it might be wise to keep it intact. For example, if the IP is 10.0.0.1 and there's already a range like 10.0.0.1/8, keeping the wide range could prevent redundancy and maintain a cleaner configuration.

3. Preserving Comments and Order:
Destroying comments and potentially losing their order could be problematic, especially if those comments hold significant context or notes that help in managing the IPs/ranges. Preserving comments and their order would be beneficial for maintaining clarity and ease of management. If feasible, updating the code to retain comments before merging the PR would be a good idea.

Please let me know if you need further input or assistance! And again: Thank you very much for doing this for us!

**Comment by favonia** [comment]
@Gamerou Thank you. About the (wide) IP ranges and their order. I have a question then. Suppose the current list is
```
99.0.0.0/20
10.0.0.0/8
10.0.0.0/16
10.0.0.1
99.0.0.0/10
10.0.0.0/24
```
and the detected IP is 10.0.0.1. Do you want to keep all items starting with "10."?

**Comment by favonia** [comment]
@Gamerou BTW, the code has been updated to implement the above algorithm and it's currently preserving comments.

**Comment by Gamerou** [comment]
Yes, your approach makes sense.

It's good that you're preserving comments. Take your time with logging, test cases, and documentation. Meanwhile, running the code from this PR sounds like a good plan. I'll integrate it into my setup as soon as I find the time.

Thanks for your efforts!

**Comment by favonia** [comment]
@Gamerou FYI: I broke this PR because I found a better way to preserve all comments. Sorry for the wait. :sweat_smile:

**Comment by favonia** [comment]
The current testing misses 4 lines of code and the documentation has not started, but this PR is dragging too long... let's merge it!

**Pull request merged**
