### PR TITLE
docs: highlight how to disable IPv6

### LINKED ISSUE #617: Improve README to highlight ways to disable IPv6

### PR DESCRIPTION
**Pull request by favonia**
Close #617.

### CODE REVIEW

**Comment by favonia** [comment]
@JvdMaat I'd like to invite you to preview the revised README at https://github.com/favonia/cloudflare-ddns/blob/ipv6/README.markdown. Do you think your past self could have easily learned that `IP6_PROVIDER=none` can disable IPv6 completely? If you think there could still be confusion, I'm happy to continue revising it. Than you again for the reporting!

**Comment by JvdMaat** [comment]
Ok, I think I just learned how to do a PR.... And I am not sure I quite did that right. But let me know if that worked for you..
(I used this PR and then added more to it).
Sorry, total noob as far at Github beyond Issues/Discussion.

**Comment by favonia** [comment]
@JvdMaat I think what you did is exactly right, except that the CI is mad about not being able to retrieve the filtering rules.

**Comment by favonia** [comment]
@JvdMaat I'll merge this, assuming all looks good. Thank you for your feedback!

**Pull request merged**
